# Generated by Django 4.0.4 on 2022-07-11 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCategoria', models.CharField(max_length=30, verbose_name='Nombre Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=150, verbose_name='Apellido')),
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Email')),
                ('contrasena', models.CharField(max_length=15, verbose_name='Contraseña')),
                ('contrasena2', models.CharField(max_length=15, verbose_name='Contraseña2')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('nombre_producto', models.CharField(max_length=20, verbose_name='Nombre Producto')),
                ('precio', models.IntegerField(verbose_name='Precio Producto')),
                ('imagen', models.ImageField(null=True, upload_to='imagenes/')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floreria.categoria')),
            ],
        ),
    ]
